### PR TITLE
Responsive Design / Restructure

### PR DESCRIPTION
**Pull request by BitDesert**
PR for #4

### CODE REVIEW

**Comment by ghost** [comment]
I've manually merged this; resolved some conflicts and changed a few minor things. Could you checkout https://github.com/dbachm123/phpNodeXRai/tree/pr4_redesign and see if the changes are  OK with you? 

see https://imgur.com/a/dJBVv

**Comment by BitDesert** [comment]
changed the way how the files are required and created another section for the server stuff

**Comment by ghost** [comment]
Could you resolve the conflicts regarding master, so I could potentially merge this in?

**Comment by BitDesert** [comment]
Couldn't get it to work with my fork repo so the PR get's through on it's own, but I could merge it locally in this repo. But I'm missing write access so I can push the new master.

**Comment by NiFNi** [comment]
I think it would be better to make the colors consistent. So either use the blue logo everywhere or the orange one. I like the orange one more as it looks pretty cool with the grey background.

**Comment by BitDesert** [comment]
@NiFNi The orange one is the official one for dark backgrounds. Would also prefer changing the blue one to orange, but that's a widget from CoinMarketCap. Maybe we can change that, but we'll have to try afterwards.

**Comment by NiFNi** [comment]
Ah okay. After merging this in I think it would be cooler to have a "selfmade" widget which style fits the rest of the page and using the api to get the data.

**Comment by ghost** [comment]
@BitDesert  

> Couldn't get it to work with my fork repo so the PR get's through on it's own, but I could merge it 
> locally in this repo. But I'm missing write access so I can push the new master.

I am not quite getting it. Are you saying that you have checked out current dbachm123:master and have merged your changes locally into master? Can you push them to a new branch on dbachm123? Then we can create a clean pull request from there, e.g. https://stackoverflow.com/questions/5066041/moving-committed-but-not-pushed-changes-to-a-new-branch

**Comment by BitDesert** [comment]
Nevermind @dbachm123 got it to work, the current branch here should work fine.

**Comment by ghost** [comment]
OK! Thanks. Will give it a try later today.

**Comment by ghost** [comment]
merged

**Pull request merged**
