### PR TITLE
monKey images for banano

### PR DESCRIPTION
**Pull request by justdmitry**
When currency is `banano` - [monKey image](http://www.monkeygen.com/) is added below price widget.

monkey

### CODE REVIEW

**Comment by justdmitry** [comment]
My changes are not perfect (from codestyle and best practices PoV), but I have no PHP knowledge. Please improve/refactor if needed.

**Comment by BitDesert** [comment]
Whoops, just realized that HTTPS for https://www.monkeygen.com does not work properly, @justdmitry do you know who is responsible for the domain?

**Comment by justdmitry** [comment]
Ping **Randomizer** on Discord, or we may try mention @Amirh24 who is owner of server and client repo...

**Comment by Amirh24** [comment]
Hi,
Yes I am aware of it, should be fixed real soon.

**Comment by Amirh24** [comment]
Please use the following endpoint in order to create the monKey image straight from the server:
http://bananomonkeys.herokuapp.com/image?address=<BANANO_ADDRESS>

**Comment by BitDesert** [comment]
@Amirh24 This could work when https://bananomonkeys.herokuapp.com/image?address=<BANANO_ADDRESS> whould redirect to a HTTPS URL too. Currently you always get redirected to a unencrypted cloudfront.net address. If you could modify the redirect to use HTTPS that would be awesome, thanks!

**Comment by Amirh24** [comment]
Changed to https

**Pull request merged**
