### PR TITLE
PR for release v1.4.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Running at http://138.197.179.164/

**Comment by ghost** [comment]
@BitDesert  I'd like to wait with releasing v1.4.0 until https://nanode21.cloud/stats.php has been fixed. Additions to the output of api.php broke something there. https://nano.meltingice.net/network looks good.

**Comment by meltingice** [comment]
@dbachm123 for what it's worth, I do some normalization of the values returned from the API to account for variations in numbers, such as commas, weird formatting, etc.

**Comment by BitDesert** [comment]
@meltingice The normalization was fixed with 1.3.9 as all the formatting was moved to the frontend.

@dbachm123 I don't think that this should be a huge problem. The voting weight is still buggy: https://monitor.nanonode.ninja/

**Comment by ghost** [comment]
@BitDesert I've found your monitor to be the only one ouf of meltingice's list with a buggy display of voting weight. Although en_US is enforced it seems to use your system locale which I suppose is de_DE, right?

**Comment by ghost** [comment]
see #47

**Comment by ghost** [comment]
OK ... v.1.4.0 looks good to me! Do we need anything else? A readme for the caching options !?

**Comment by BitDesert** [comment]
Currently testing with a docker image for the monitor. Do we want to include more statistics on block types and peer versions in v1.4.0? Like at https://nano.nifni.net/

**Comment by ghost** [comment]
I'd prefer to have this in a follow-up release and roll the caching feature out rather quickly to reduce some stress on the nodes from all  the various network monitors that are being implemented at the moment.  Also, I am personally not a fan of having all those statistics on the monitor's front page. To be honest, it's even a bit too cluttered for me in it's current state. Maybe a tabbed interface would make sense, or the possibility to fold/u fold some blocks of information !? I feel we should not rush this. Maybe in the api, if needed in some other monitoring solutions, and not yet on the front-end !? I  would like to keep the node monitor as a node monitor and leave some second-level statistics (network, comparison of different nodes, etc.) to tools like ninja or nanode21.

Info on delegates (similar to the old raiblocks.net explorer) would be my top pick to work on next.

**Comment by BitDesert** [comment]
Alright, I'm merging and create a release.

**Comment by ghost** [comment]
Awesome, just wanted to do that as well 😆

**Comment by ghost** [comment]
Does the caching warrant an r/nanocurrency post?

**Comment by BitDesert** [comment]
Sure, why not? ;)

**Comment by ghost** [comment]
Will do that now ... btw, what's the best way to get the develop branch up to date with master again? I am not used to having a static develop branch around ... usually, I delete the feature / dev branches after merging.

**Comment by BitDesert** [comment]
Master isn't usually pushed to, I do it usually like a waterfall from feature->develop->master.
Master is always the released version, develop is the next version to release. Only hotfixes should be merged to directly to master.

**Comment by ghost** [comment]
Yes of course .... after a release, the dev branch is 1 commit behind master (because of the merge commit on master). So one needs to merge master back into the dev branch to have the dev branch at the same level as master. Wondering if there is a better way.

**Comment by BitDesert** [comment]
I think this should be possible with fast forward without a merge commit

**Pull request merged**
