### PR TITLE
Add FileCache

### PR DESCRIPTION
**Pull request by BitDesert**
Simple FileCache that writes to `/tmp` for #37

### CODE REVIEW

**Comment by ghost** [comment]
Looks good to me. 
Can you merge in the styleci fixes? 

Will deploy it to my node and watch it for a while later.

**Review by ghost — CHANGES_REQUESTED** [review]
Looks good to me.
Can you merge in the styleci fixes?

**Comment by ghost** [comment]
While thinking a bit more about that: This would only reduce RPC load within a single connection, as the cache is not global, right? So RPC could still be spammed via a botnet via lots of individual connections.

**Comment by BitDesert** [comment]
No, this is a cache for the whole monitor and server side.
StyleCI merged

**Review by ghost — APPROVED** [review]

**Pull request merged**
