### PR TITLE
v.1.4.6 

### PR DESCRIPTION
**Pull request by ghost**
This PR mainly involves a proper banano theme for the node monitor. 
Live at: http://185.243.9.164/ (Nano) and http://138.197.179.164/ (Banano).

### CODE REVIEW

**Comment by ghost** [comment]
Fix for #70

**Comment by BitDesert** [comment]
Should we tie the switch Nano/Banano to a specific theme? I would suggest adding a config option for that. Otherwise we could get problems when we want for example a dark banano theme.

**Comment by ghost** [comment]
You're right. Will decouple currency type from theme and update this PR.

**Comment by ghost** [comment]
Fixed #70, #71, and #80

**Comment by ghost** [comment]
Addressed #72

**Pull request merged**
