### PR TITLE
Implemented basic Google Analytics Tracking

### PR DESCRIPTION
**Pull request by devlsh**
Pretty simple - at some point I'd like to go through the entire project and standardise formatting, perhaps even put forward a proposal for which best practises the project should adopt within PHP. Let me know if this is okay (Otherwise I don't want to waste either of our time)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good to me.

**Comment by devlsh** [comment]
@BitDesert Any chance you could approve this asap?

**Review by BitDesert — APPROVED** [review]
Looks good

**Comment by ghost** [comment]
Will merge this into the 'develop' branch, targeted for the next release v.1.4.7

**Pull request merged**
